version: '3.9'

services:
  web-blue:
    image: krishnavamshi933/budget-app-web-blue:latest
    ports:
      - "3001:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - budget-net

  web-green:
    image: krishnavamshi933/budget-app-web-green:latest
    ports:
      - "3002:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - budget-net

  db:
    image: postgres:15.3
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - budget-net

  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - budget-net

  redis2:
    image: redis:7.2.5
    ports:
      - "6380:6379"
    volumes:
      - redis2-data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - budget-net

  sidekiq:
    image: krishnavamshi933/budget-app-sidekiq:latest
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    volumes:
      - .:/app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
      - REDIS2_URL=redis://redis2:6379/0
    networks:
      - budget-net

  nginx:
    image: krishnavamshi933/budget-app-nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - web-blue
      - web-green
    networks:
      - budget-net

volumes:
  pgdata:
  redis-data:
  redis2-data:

networks:
  budget-net:
    driver: overlay
