name: Docker Compose Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} <<EOF
            cd /home/ubuntu/workspace/Budget-App/    # path of docker-compose file 
            docker-compose pull
            docker-compose up -d
            docker image prune -f
            docker-compose ps -a
          EOF
